
filebeat.inputs:
- type: filestream
  # Unique ID among all inputs, an ID is required.
  id: my-filestream-id

  # Change to true to enable this input configuration.
  enabled: true

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /var/log/*.log

# ---------------------------- Redis Output ----------------------------
output.redis:
  hosts: ["redis-19004.c299.asia-northeast1-1.gce.cloud.redislabs.com:19004"]
  user: "default"
  password: "B9NelJhy35TDqihDp9YeUq1xl6srVYZB"
  key: "filebeat"
  db: 0
  timeout: 5

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
